version: 2
jobs:
  deploy:
    docker:
      - image: 872035818801.dkr.ecr.us-east-2.amazonaws.com/boaweb/deploy-igc:latest

    steps:
      - run: deploy
workflows:
  version: 2
  daily:
    triggers:
      - schedule:
          cron: "0/5 * * * *"
          filters:
            branches:
              only:
                - master
           
    jobs:
      - deploy
