version: 2
jobs:
  deploy:
    working_directory: ~/circulate
    docker:
      - image: mehdi8/amazonlinux-build:latest
      auth:
          username: $DOCKERHUB_USERNAME  # can specify string literal values
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: deploy 
