version: 2
jobs:
  build:
    docker:
      - image: mehdi8/boaweb:latest
        auth:
          username: $DOCKERHUB_USERNAME  # can specify string literal values
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: deploy
